use async_trait::async_trait;
use mongodb::{bson::{doc, oid::ObjectId, DateTime as BsonDateTime}, Collection, Database};
use anyhow::{Result, anyhow, Context}; // anyhow is used by the trait, Context for error wrapping
use chrono::Utc; // For default created_at/updated_at if needed during creation

use crate::domain::entities::project::Project as DomainProject;
use crate::domain::repositories::project_repository::ProjectRepository as DomainProjectRepository;
use super::project_model::ProjectModel; // Existing MongoDB model

pub struct ProjectRepository {
    collection: Collection<ProjectModel>,
}

impl ProjectRepository {
    pub fn new(db: &Database) -> Self {
        let collection = db.collection::<ProjectModel>("projects");
        Self { collection }
    }
}

#[async_trait]
impl DomainProjectRepository for ProjectRepository {
    async fn find_by_number(&self, number: i32) -> Result<Option<DomainProject>> {
        let model = self
            .collection
            .find_one(doc! { "number": number }, None)
            .await
            .context(format!("Failed to find project by number: {}", number))?;
        Ok(model.map(DomainProject::from)) // Uses From<ProjectModel> for DomainProject
    }

    async fn create(&self, domain_project: &DomainProject) -> Result<DomainProject> {
        // The From<DomainProject> for ProjectModel in project_model.rs already handles setting timestamps
        // and using domain_project.id.unwrap_or_else(ObjectId::new) for _id.
        let model_to_insert = ProjectModel::from(domain_project.clone());

        let result = self
            .collection
            .insert_one(model_to_insert, None) // model_to_insert already has _id set if domain_project.id was None
            .await
            .context("Failed to insert new project into MongoDB")?;

        // The ID is either what came from domain_project.id or newly generated by ObjectId::new()
        // in the From trait. If it was newly generated, result.inserted_id will match that.
        // If domain_project.id was Some(id), then model_to_insert._id was that id, and result.inserted_id should match.
        let inserted_id = match result.inserted_id.as_object_id() {
            Some(oid) => oid,
            None => { // This case should ideally not happen if using ObjectIds and From trait is correct
                return Err(anyhow!("MongoDB did not return an ObjectId after insert"));
            }
        };
        
        let created_project = DomainProject {
            id: Some(inserted_id),
            ..domain_project.clone()
        };
        Ok(created_project)
    }

    async fn find_or_create(&self, project_number: i32, name: &str) -> Result<DomainProject> {
        if let Some(existing_project) = self.find_by_number(project_number).await? {
            Ok(existing_project)
        } else {
            // Project not found, create it.
            // DomainProject does not have created_at/updated_at fields.
            // These are handled by ProjectModel::from(DomainProject), which sets them to Utc::now().
            let project_to_create = DomainProject {
                id: None, // Will be generated by DB or `create` method's From trait logic
                name: name.to_string(),
                number: project_number,
            };
            self.create(&project_to_create).await
        }
    }
}
